### ISSUE TITLE
Add Donate Link

### ISSUE THREAD

**Issue by leoherzog** [mp3chapters/mp3chapters.github.io#18]
This tool rules. Thank you for creating it, and thank you even more for open-sourcing it. Please consider adding a way for us to buy you a coffee in the tool itself, or at least in the README.

**Comment by DominikPeters** [comment]
Thanks for your comment, I'm very glad you like the tool. Regarding donations, since I'm technically a French government official, I'd need to ask permission to receive that type of income, and I don't really want to bother with that. But if you like, feel free to make a donation to the Against Malaria Foundation in my name :)
